general {
    no_fade_in = false
    grace = 300
    disable_loading = true
}

background {
    monitor =
    path = /home/vs-horcrux/wallpaper   # Update to your actual wallpaper path
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2 # 0 disables blurring
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# TIME
label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 64
    font_family = JetBrains Mono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text = Hello, $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 20
    font_family = JetBrains Mono Nerd Font
    position = 0, 0
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgb(95, 108, 138) # Matches your Rofi lime-ish/blue
    inner_color = rgb(30, 32, 36)
    font_color = rgb(200, 200, 200)
    fade_on_empty = true
    placeholder_text = <i>Password...</i> # Text rendered in the input box
    hide_input = false
    rounding = 10 # Matches your Hyprland rounding
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34) # if authentication failed, changes outer_color and fail message color
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
    position = 0, -80
    halign = center
    valign = center
}
