# Generated automatically from colors.env
# Target location: ./hypr/colors.conf

$border_active   = rgba(5f6c8aff)
$border_inactive = rgba(595959aa)
$shadow_color    = rgba(1a1a1aee)

$gaps_in      = 3
$gaps_out     = 15
$border_size  = 3
$rounding     = 0
