# Generated automatically from colors.env
# Target location: ./hypr/colors.conf

$border_active   = rgba(ff0000ff) rgba(ffffff66) 45deg
$border_inactive = rgba(595959aa)
$shadow_color    = rgba(1a1a1aee)

$gaps_in      = 5
$gaps_out     = 15
$border_size  = 2
$rounding     = 5
