# Main Hyprland Config

# # Shared Configs
# source = ~/.config/hypr/shared/programs.conf
# source = ~/.config/hypr/shared/monitors.conf
# source = ~/.config/hypr/shared/autostart.conf
# source = ~/.config/hypr/shared/environment.conf
# source = ~/.config/hypr/shared/input.conf

# # Load default config files
# source = ~/.config/hypr/default/looknfeel.conf
# source = ~/.config/hypr/default/keybindings.conf
# source = ~/.config/hypr/default/windows.conf

# # Load custom config files
# source = ~/.config/hypr/custom/looknfeel.conf
# source = ~/.config/hypr/custom/keybindings.conf
# source = ~/.config/hypr/custom/windows.conf

source = ~/.config/hypr/shared/programs.conf
source = ~/.config/hypr/shared/monitors.conf
source = ~/.config/hypr/shared/autostart.conf
source = ~/.config/hypr/shared/environment.conf
source = ~/.config/hypr/shared/input.conf

source = ~/.config/hypr/frags/looknfeel.conf
source = ~/.config/hypr/frags/keybindings.conf
source = ~/.config/hypr/frags/windows.conf