# Window/Workspace Rules

windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Uncomment if needed
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# windowrulev2 = opacity 1, class:^(kitty)$
# windowrulev2 = opacity 1, class:^(Code)$

# windowrule=opacity .9 0.8,class:^(Code)$

windowrulev2 = workspace 2,class:^(spotify)$

windowrulev2 = float,class:^(org\.pulseaudio\.pavucontrol)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(nm-connection-editor)$
windowrulev2 = float,class:^(Tk)$,title:^(Keybindings Viewer & Checker)$
windowrulev2 = float,class:^(Tk)$,title:^(Wallpaper Picker)$
windowrulev2 = float,title:^(Hyprland Themer)$

# workspace = f[1], gapsout:0, gapsin:0, border:0
workspace = f[1], border:0

# Forces 1.0 opacity for both states on floating windows
windowrulev2 = opacity 1.0 override 1.0 override, floating:1

windowrule = float, class:^(org.gnome.SystemMonitor)$
windowrule = size 1000 600, class:^(org.gnome.SystemMonitor)$
windowrule = center, class:^(org.gnome.SystemMonitor)$

windowrule = float, class:^(nmtui-float)$
windowrule = size 1000 600, class:^(nmtui-float)$
windowrule = center, class:^(nmtui-float)$

###############################################33


