[global]
    # Default border outline styling
    frame_color = "#813737"

[urgency_low]
    background = "#401717"
    foreground = "#FFFFFF"

[urgency_normal]
    background = "#330a00"
    foreground = "#FFFFFF"

[urgency_critical]
    background = "#1C1E27"
    foreground = "#FFFFFF"
    frame_color = "#BF616A" # Reddish highlight for critical
