# Example: Uncomment to autostart apps
# exec-once = $terminal
# exec-once = nm-applet &

# Example: Uncomment to autostart apps
# exec-once = $terminal
# exec-once = nm-applet &
exec-once = hyprpaper
exec-once = sh /home/vs-horcrux/.config/waybar/launch.sh
exec-once = hypridle

# Unlock keyring on startup
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gnome-keyring-daemon --start --components=secrets
