$terminal = kitty
$browser = notify-send "Browser" && brave-browser --password-storage=basic
$fileManager = thunar
$menu = /home/vs-horcrux/.config/rofi/ai_rofi/launchers/neatblackandtheme.sh
$music = spotify-launcher
$wpswitcher = sh /home/vs-horcrux/Desktop/workdir/dots/hypr-setup/extra-utils/wallpaper-switcher/wp-switcher-wrapper.sh
$editor = gedit
$code = antigravity
$chat = flatpak run dev.vencord.Vesktop 
